language: ruby

services:
  - postgresql

bundler_args: "--without development"

cache: bundler

before_script:
  - cp config/database.yml.travis config/database.yml

script:
  - bin/rails db:migrate RAILS_ENV=test
  - bin/rails test