language: ruby

services:
  - postgresql

bundler_args: "--without development production"

cache: bundler

before_script:
  - cp config/database.yml.travis config/database.yml
  - bin/rails db:migrate RAILS_ENV=test

script:
  - bin/rails test